export enum AUTH_ACTIONS_REQUEST {
  REGISTRATION_SUCCESS = "@auth/REGISTRATION_SUCCESS",
  REGISTRATION = "@auth/REGISTRATION",

  LOGIN_SUCCESS = "@auth/LOGIN_SUCCESS",
  LOGOUT = "@auth/LOGOUT",
  LOGIN = "@auth/LOGIN",

  CLEAN_REQUEST_ERROR = "@auth/CLEAN_REQUEST_ERROR",
  REQUEST_ERROR = "@auth/REQUEST_ERROR",
  REQUEST = "@auth/REQUEST",
}
