export enum CART_ACTIONS_REQUEST {
  REMOVE_ALL_PRODUCTS_FROM_CART = "@shoppingCart/REMOVE_ALL_PRODUCTS_FROM_CART",
  REMOVE_PRODUCT_FROM_CART = "@shoppingCart/REMOVE_PRODUCT_FROM_CART",
  ADD_PRODUCT_TO_CART = "@shoppingCart/ADD_PRODUCT_TO_CART",
}
